package com.wuba.mobile.compiler.util;

/**
 * author : wangqiang
 * date : 2018/8/14
 * desc :
 */
public interface Consts {

    String OPTION_MODULE_NAME = "moduleName";
    String BASE_PACKAGE_NAME = "com.wuba.mobile.middle.mis.protocol.router";

    String ACTIVITY_FULL_NAME = "android.app.Activity";
    String FRAGMENT_FULL_NAME = "android.app.Fragment";
    String FRAGMENT_V4_FULL_NAME = "android.support.v4.app.Fragment";

    String METHOD_HANDLE = "handle";
    String ROUTE_TABLE = "RouteTable";
    String ROUTE_TABLE_FULL_NAME = BASE_PACKAGE_NAME + ".table." + ROUTE_TABLE;
    String APT_PACKAGE_NAME = "com.wuba.mis.router.apt";
    String CLASS_JAVA_DOC = "Generated by Router. Do not edit it!\n";
}
